server:
  port: 9999

spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql:///stsm_db
  redis:
    port: 6379
    host: localhost
# 返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


# 日志打印级别
logging:
  level:
    edu.sust: debug

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

alipay:
  appId: 2021000122685401
  #应用私钥
  appPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCRq8Pn0jn81pvAireS5OvPFqvR7ZUV4xKRCrR/J5AeZ7RVLFn2fvDCNbImCBLA5neyXP4FiWwMx6MNs19hGk6ODMF41KlLlRNracVGALgdvhRcP8FQWs3NR1MrLTIT6+0d5rm9pmdhY7+ud3rkMGOtU+oX8kEpOVHY0oyTNpBVg1j8zX11jkuTnpKrCoiXvn6jrodQbTYu1yEZ5KiCFwm/Iq9+NC+fA/aJMEgzfOOV7SkknIXXyFdGNgcXaRkFcIbKLA3rKiKCju+WPvjaZACqJCl8DetDceJzrmge5rUDC4GyimH4QPDqeptDvFGRh7yJQUyJjr4+MlcdwnIo2wGrAgMBAAECggEAfUObPyoEO2vAm52tpl+8d2QjdG49GYkeWiM+e2lmAP9kjymIYvNdzWOnQhUHK2ID5BkbR1+YzpSNniZ1Cmc4zeYiKOmWeyxCeseFoGDV8p2VnI4mihbLio6e8i33NjJWwLO7XV5O3+yK1FhiEP+bd10FnHnxlqV3wF+uCpmNHDp61h9yiAiffD6fotPzxAdT/f7SdYTndfH/6CCS2HoVpFr5DgmEpNp4r3nigOrudLNwDNEWsJNcGCTv/GxTj2CoKF4SC2smzmN5Wxbw+aIx5NCKVwmN2xroUPL676izpoDE3oUXGkm1N1drNuo6jHGI65ybtm5JeGTXYP84NTzrIQKBgQDgbfFxwIFKtzpT40/NPpEpEiPW4YL6HsLryESmea8wadAvEO0f2sPOUBthYelPPc5FT+IovR/5QeM/XEbSrNFv6qdGLg5LAS6PIMMJf1C0qkGPW11TyV89SP9b0M1FAKHD+IgasDJkw9OzHXUacyn7SulRC1oiduIFQfqzyTWFzQKBgQCmKZrUdDktZGLPcdvhc4vRuDH2RylV1Vig/F5F1tnuFztdVerMne8FKe8nM307o5Kqxn7bx3u8+gQjkz+16Z5iAJQM5+mOBKCuq4VdckhR1jEQmW5paZIhRRaZv4T40QZHwC2IybKSeC3FzBfI0Dc++eO7hSMvCTA7ckEK3jutVwKBgFsozTWjN+EdY7fHURbRHy1LjPsvRoBKFmqnQhtMufg0QrebbHXP6lDXAQghOR9Sv4Iv3HEnwOEB/kgyNyJDyB5pdeBvvKaCqGLCr/YfnKyFq3OLbPEnjmPaTr8ApSAuDYcIYGBWyWFcmZTblkFUHe1QlEyzC72MBGqWTjrQs8jRAoGAFKSqlaZyzA7ir78HgDTos/9cRaqFmiJNRoLT+307yfac63WXHCCq50tUaNxevKAPwqOycv+PgeTVys2qZqFFigtkWU4emAQ/KjQo93kRPwmLQvKs4u+4teVtb2B51qexTgy0G4BjbQr9NMusUMh9dJd7EXry6g8MLPZ+2ijN5TUCgYEAjKzhGqEx//qVaLlLWnwOnZwQ1dsiEoFq6TGxbAQz4Ep0Wrqr5zeBdPQ0TwSQEh7l21TZht1ahk5NiQeOmc3qkc4Id1PHE6jFt9y1jwfnUyQYEiXrr4UyTgxck6b7C+08HnB+bEqdkrTjJlqmGxwtHpHEaxsmoSw6BVENb+JodFo=
  #支付宝公钥
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiAg7xaSn1AxqrGAmbMwebGytVd3dLmMHjD58zjNJ7YOiA2KNYjGqzw5Nm1h7aASnWTHkc1s3axtbKi49fM/Yc8e8EyCq+MSUbD/LA72/0+S5cZ/1FsOV/k59F+7vcSwg3BM7S9sREpwYSjJBtQFjrmRQb+b0pq+tLQdolm8AFQjqUYv+PWYsR+O1EC67hVo9kDkCtwTRCyTxcwMDxjvWZcQAAGzu4ickxUMQWcFNzpwdS4sXAao3EB9mgB+bnK64chp5+wNrmaHy1NnMtbKNwUyo0ktj5/kJYQvZGvtGmTWEP3JrMCrbYjZT3UdnRpnZbAfTPkSd6dWZeEvlDucGdQIDAQAB
  #支付成功的回调，更新订单的状态
  notifyUrl: http://wx73es.natappfree.cc/alipay/notify
